apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: mycluster
 region: ap-south-1

nodeGroups:
  - name: node-1
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
       publicKeyName: mykey222

  - name: node-2
    desiredCapacity: 1
    instanceType: t2.small
    ssh:
       publicKeyName: mykey222

