apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - efs-provisioner.yml
  - rbac.yml
  - storage.yml
  - mysql.yml
  - drupal.yml